name: Test

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
      
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      default_branch: regs/heads/master
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install poetry
        run: pipx install poetry
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
          cache: 'poetry'

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('poetry.lock') }}

      - name: Poetry version
        run: poetry --version

      - name: Install dependencies
        run: poetry install

      - name: Test
        run: poetry run pytest
