name: Release
on:
  release:
    types:
      - created

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      default_branch: regs/heads/master
      python_version: 3.8
      poetry_version: 1.0.0
      registry: ghcr.io
      name: datahub-sap-hana
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install poetry
        run: pipx install poetry
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
          cache: 'poetry'

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('poetry.lock') }}

      - name: Poetry version
        run: poetry --version

      ### Generate metadata
      - name: Get Repo Owner
        id: get_repo_owner
        run: >
          echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} |
          tr '[:upper:]' '[:lower:]')

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ steps.get_repo_owner.outputs.repo_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.registry }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.registry }}/${{ steps.get_repo_owner.outputs.repo_owner }}/${{ env.name }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Get metadata
        id: metadata
        uses: contiamo/git-metadata-action@main

      ### Build steps

      - name: Install dependencies
        run: poetry install

      - name: Build
        run: poetry build

      - name: Checksums
        working-directory: ./dist
        run: shasum -a 256 * > checksums.txt

      ### Push artifacts
      - name: Docker build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          outputs: "type=registry,push=true"
          platforms: linux/amd64
          labels: ${{ steps.docker_meta.outputs.labels }}
          tags: |
            ${{ env.registry }}/${{ steps.get_repo_owner.outputs.repo_owner }}/${{ env.name }}:latest
            ${{ env.registry }}/${{ steps.get_repo_owner.outputs.repo_owner }}/${{ env.name }}:${{ steps.metadata.outputs.semver }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ steps.metadata.outputs.semver }}
          overwrite: true
          file_glob: true
